run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - govet
    - errcheck
    - unused
    - ineffassign
    - misspell
    - gofmt
    - goimports
    - gosec
    - staticcheck
    
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: (third_party|builtin|examples)/
      linters:
        - all

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/death-star/command-core
